// Filter Options Constants
// Separate data for "Bộ/Ban/Ngành" (Department) and "Tỉnh/Thành phố" (Province)

import type { FilterOptions } from '../types/filter-options';

/**
 * Filter options for "Bộ/Ban/Ngành" (Department) search
 * Data from API: Implementing Agencies (Cơ quan thực hiện)
 */
export const DEPARTMENT_FILTER_OPTIONS: FilterOptions = {
    implementingAgencies: [
        { id: "6369", name: "Bộ Công an" },
        { id: "94", name: "Bộ Công thương" },
        { id: "5096", name: "Bộ Dân tộc và Tôn giáo" },
        { id: "2", name: "Bộ Giáo dục và Đào tạo" },
        { id: "734", name: "Bộ Khoa học và Công nghệ" },
        { id: "857", name: "Bộ Ngoại giao" },
        { id: "924", name: "Bộ Nội vụ" },
        { id: "1053", name: "Bộ Nông nghiệp và Môi trường" },
        { id: "6407", name: "Bộ Quốc phòng" },
        { id: "1301", name: "Bộ Tài chính" },
        { id: "4019", name: "Bộ Tư pháp" },
        { id: "5119", name: "Bộ Văn hóa, Thể thao và Du lịch" },
        { id: "4851", name: "Bộ Xây dựng" },
        { id: "4881", name: "Bộ Y tế" },
        { id: "363963", name: "Ngân hàng Chính sách xã hội" },
        { id: "4983", name: "Ngân hàng Nhà nước Việt Nam" },
        { id: "363973", name: "Ngân hàng phát triển Việt Nam" },
        { id: "6468", name: "Thanh tra Chính phủ" },
        { id: "431093", name: "Tòa án nhân dân" },
        { id: "364400", name: "Tập đoàn Điện lực Việt Nam" },
        { id: "6491", name: "Văn phòng Chính phủ" },
        { id: "456442", name: "Văn phòng Chính phủ" },
        { id: "463832", name: "Văn phòng Trung ương Đảng" },
    ],
    fields: [
        { id: "67", name: "An toàn bức xạ và hạt nhân(Bộ Khoa học và Công nghệ)" },
        { id: "13754", name: "An toàn đập, hồ chứa thuỷ điện(Bộ Công Thương)" },
        { id: "14422", name: "An toàn lao động trong thi công xây dựng công trình(Bộ Xây dựng)" },
        { id: "13", name: "An toàn thực phẩm(Bộ Công Thương)" },
        { id: "246", name: "An toàn thực phẩm(Bộ Y tế)" },
        { id: "72", name: "An toàn, vệ sinh lao động(Bộ Nội vụ)" },
        { id: "14", name: "An toàn vệ sinh lao động(Bộ Công Thương)" },
        { id: "16062", name: "An toàn vệ sinh lao động(Bộ Quốc phòng)" },
        { id: "15143", name: "Bộ Tài chính(Bộ Tài chính)" },
        { id: "187", name: "Báo chí(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "145", name: "Báo chí(Bộ Quốc phòng)" },
        { id: "84", name: "Báo chí(Bộ Ngoại giao)" },
        { id: "16042", name: "Bậc kỹ thuật nghề(Bộ Quốc phòng)" },
        { id: "198", name: "Bồi thường nhà nước(Bộ Tư pháp)" },
        { id: "16025", name: "Biên giới lãnh thổ(Bộ Ngoại giao)" },
        { id: "180", name: "Biến đổi khí hậu(Bộ Nông nghiệp và Môi trường)" },
        { id: "174", name: "Biển và hải đảo(Bộ Nông nghiệp và Môi trường)" },
        { id: "76", name: "Bình đẳng giới(Bộ Nội vụ)" },
        { id: "215", name: "Bản quyền tác giả(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "15662", name: "Bảo đảm an ninh hàng không(Bộ Công an)" },
        { id: "15842", name: "Bảo đảm trật tự, an toàn giao thông đường bộ(Bộ Công an)" },
        { id: "162", name: "Bảo hiểm(Bộ Tài chính)" },
        { id: "16522", name: "Bảo hiểm xã hội(Bộ Tài chính)" },
        { id: "73", name: "Bảo hiểm xã hội(Bộ Nội vụ)" },
        { id: "16382", name: "Bảo hiểm y tế(Bộ Y tế)" },
        { id: "14602", name: "Bảo tồn thiên nhiên và Đa dạng sinh học(Bộ Nông nghiệp và Môi trường)" },
        { id: "74", name: "Bảo trợ xã hội(Bộ Y tế)" },
        { id: "16104", name: "Bảo vệ Bí mật nhà nước(Bộ Y tế)" },
        { id: "13851", name: "Bảo vệ công trình quốc phòng và khu quân sự(Bộ Quốc phòng)" },
        { id: "14622", name: "Bảo vệ dữ liệu cá nhân(Bộ Công an)" },
        { id: "15882", name: "Bảo vệ môi trường ngành Công Thương(Bộ Công Thương)" },
        { id: "15262", name: "bảo vệ quyền lợi người tiêu dùng(Bộ Công Thương)" },
        { id: "14968", name: "Bảo vệ vành đai an toàn kho đạn dược(Bộ Quốc phòng)" },
        { id: "188", name: "Bưu chính(Bộ Khoa học và Công nghệ)" },
        { id: "13854", name: "Các cơ sở giáo dục khác(Bộ Giáo dục và Đào tạo)" },
        { id: "13902", name: "Các dịch vụ hỗ trợ(Điện Lực)" },
        { id: "13711", name: "Các hoạt động khác của NHPT(Ngân hàng phát triển)" },
        { id: "116", name: "Chế biến và phát triển thị trường Nông sản(Bộ Nông nghiệp và Môi trường)" },
        { id: "16542", name: "Chế độ, chính sách đối với nhà giáo(Bộ Giáo dục và Đào tạo)" },
        { id: "115", name: "Chăn nuôi(Bộ Nông nghiệp và Môi trường)" },
        { id: "13762", name: "Chi trả các chế độ BHXH(Bộ Tài chính)" },
        { id: "97", name: "Chính quyền địa phương(Bộ Nội vụ)" },
        { id: "3", name: "Chính sách(Bộ Công an)" },
        { id: "131", name: "Chính sách(Bộ Quốc phòng)" },
        { id: "149", name: "Chính sách Thuế(Bộ Tài chính)" },
        { id: "150", name: "Chứng khoán(Bộ Tài chính)" },
        { id: "15562", name: "Chứng nhận chất lượng an toàn kỹ thuật và bảo vệ môi trường(Bộ Công an)" },
        { id: "86", name: "Chứng nhận lãnh sự, hợp pháp hóa lãnh sự(Bộ Ngoại giao)" },
        { id: "14442", name: "Chứng nhận xuất trình(Bộ Ngoại giao)" },
        { id: "199", name: "Chứng thực(Bộ Tư pháp)" },
        { id: "132", name: "Chứng thực điện tử(Bộ Quốc phòng)" },
        { id: "16362", name: "chất lượng sản phẩm hàng hóa(Bộ Công Thương)" },
        { id: "16562", name: "Chuẩn tiếp cận pháp luật(Bộ Tư pháp)" },
        { id: "15342", name: "Chuyển đổi công ty nhà nước được thành lập và hoạt động theo Luật Doanh nghiệp nhà nước thành công ty trách nhiệm hữu hạn một thành viên tổ chức và hoạt động theo quy định tại Luật Doanh nghiệp(Bộ Tài chính)" },
        { id: "14947", name: "Chuyển nhượng vốn(Bộ Quốc phòng)" },
        { id: "96", name: "Cải cách hành chính(Bộ Nội vụ)" },
        { id: "15202", name: "Cụm Công nghiệp(Bộ Công Thương)" },
        { id: "98", name: "Công chức, viên chức(Bộ Nội vụ)" },
        { id: "200", name: "Công chứng(Bộ Tư pháp)" },
        { id: "87", name: "Công chứng, chứng thực(Bộ Ngoại giao)" },
        { id: "15764", name: "Công chứng (nội bộ)(Bộ Tư pháp)" },
        { id: "14967", name: "Công nghệ thông tin(Bộ Quốc phòng)" },
        { id: "189", name: "Công nghệ thông tin, điện tử(Bộ Khoa học và Công nghệ)" },
        { id: "15282", name: "Công nghệ thông tin và chuyển đổi số(Bộ Tài chính)" },
        { id: "15", name: "Công nghiệp địa phương(Bộ Công Thương)" },
        { id: "16", name: "Công nghiệp nặng(Bộ Công Thương)" },
        { id: "16402", name: "Công nghiệp quốc phòng, an ninh(Bộ Quốc phòng)" },
        { id: "17", name: "Công nghiệp tiêu dùng(Bộ Công Thương)" },
        { id: "15123", name: "Công tác cán bộ(Bộ Công Thương)" },
        { id: "16004", name: "Công tác cán bộ(Bộ Ngoại giao)" },
        { id: "272", name: "Công tác dân tộc(Dân tộc và Tôn giáo)" },
        { id: "16302", name: "Công tác dân tộc, tín ngưỡng, tôn giáo(Dân tộc và Tôn giáo)" },
        { id: "13700", name: "Công tác lãnh sự(Bộ Ngoại giao)" },
        { id: "15124", name: "Công tác pháp chế(Bộ Công Thương)" },
        { id: "14942", name: "Công tác quân sự quốc phòng(Bộ Quốc phòng)" },
        { id: "99", name: "Công tác thanh niên(Bộ Nội vụ)" },
        { id: "15502", name: "Công tác văn phòng(Bộ Công Thương)" },
        { id: "14862", name: "Công tác Văn phòng(Văn phòng Chính phủ)" },
        { id: "14965", name: "Công tác văn phòng(Bộ Quốc phòng)" },
        { id: "15126", name: "Công Thương địa phương(Bộ Công Thương)" },
        { id: "36", name: "Cơ sở vật chất và thiết bị trường học(Bộ Giáo dục và Đào tạo)" },
        { id: "133", name: "Cơ yếu(Bộ Quốc phòng)" },
        { id: "85", name: "Cấp hộ chiếu, giấy thông hành, công hàm đề nghị cấp thị thực(Bộ Ngoại giao)" },
        { id: "1", name: "Cấp, quản lý căn cước(Bộ Công an)" },
        { id: "13760", name: "Cấp sổ BHXH, thẻ BHYT(Bộ Tài chính)" },
        { id: "88", name: "Cấp thị thực, gia hạn tạm trú(Bộ Ngoại giao)" },
        { id: "14948", name: "Cung cấp thông tin về liệt sĩ, mộ liệt sĩ(Bộ Quốc phòng)" },
        { id: "16442", name: "Dữ liệu(Bộ Công an)" },
        { id: "158", name: "Dự trữ(Bộ Tài chính)" },
        { id: "16202", name: "Dự trữ nhà nước(Bộ Tài chính)" },
        { id: "134", name: "Dân quân tự vệ(Bộ Quốc phòng)" },
        { id: "247", name: "Dân số, Bà mẹ - Trẻ em(Bộ Y tế)" },
        { id: "15862", name: "Dịch vụ công trong Đảng(Văn phòng Trung ương Đảng)" },
        { id: "13900", name: "Dịch vụ cung cấp điện mới(Điện Lực)" },
        { id: "14100", name: "Dịch vụ du lịch khác(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "16203", name: "Dịch vụ tài chính(Bộ Tài chính)" },
        { id: "19", name: "Dịch vụ thương mại(Bộ Công Thương)" },
        { id: "13901", name: "Dịch vụ trong quá trình thực hiện HĐMBĐ(Điện Lực)" },
        { id: "216", name: "Di sản văn hóa(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "16043", name: "Doanh trại(Bộ Quốc phòng)" },
        { id: "18", name: "Dầu khí(Bộ Công Thương)" },
        { id: "15583", name: "dầu khí(Bộ Công Thương)" },
        { id: "14382", name: "Du lịch(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "249", name: "Dược phẩm(Bộ Y tế)" },
        { id: "16005", name: "Đào tạo bồi dưỡng(Bộ Ngoại giao)" },
        { id: "100", name: "Đào tạo, bồi dưỡng cán bộ công chức, viên chức(Bộ Nội vụ)" },
        { id: "248", name: "Đào tạo và Nghiên cứu khoa học(Bộ Y tế)" },
        { id: "49", name: "Đăng kiểm(Bộ Xây dựng)" },
        { id: "201", name: "Đăng ký biện pháp bảo đảm(Bộ Tư pháp)" },
        { id: "89", name: "Đăng ký công dân(Bộ Ngoại giao)" },
        { id: "4", name: "Đăng ký, quản lý con dấu(Bộ Công an)" },
        { id: "5", name: "Đăng ký, quản lý cư trú(Bộ Công an)" },
        { id: "6", name: "Đăng ký, quản lý phương tiện giao thông cơ giới, xe máy chuyên dùng(Bộ Công an)" },
        { id: "16002", name: "Đối ngoại(Bộ Ngoại giao)" },
        { id: "144", name: "Đối ngoại quốc phòng(Bộ Quốc phòng)" },
        { id: "176", name: "Địa chất và khoáng sản(Bộ Nông nghiệp và Môi trường)" },
        { id: "20", name: "Điện(Bộ Công Thương)" },
        { id: "15462", name: "Điện lực(Bộ Công Thương)" },
        { id: "217", name: "Điện ảnh(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "15642", name: "Đảm bảo an toàn thông tin, an ninh mạng(Bộ Công an)" },
        { id: "14962", name: "Động viên công nghiệp(Bộ Quốc phòng)" },
        { id: "135", name: "Động viên quân đội(Bộ Quốc phòng)" },
        { id: "14522", name: "Định danh và xác thực điện tử(Bộ Công an)" },
        { id: "177", name: "Đo đạc, bản đồ và thông tin địa lý(Bộ Nông nghiệp và Môi trường)" },
        { id: "175", name: "Đất đai(Bộ Nông nghiệp và Môi trường)" },
        { id: "197", name: "Đấu giá tài sản(Bộ Tư pháp)" },
        { id: "56", name: "Đấu thầu(Bộ Tài chính)" },
        { id: "13708", name: "Đấu thầu lựa chọn nhà đầu tư(Bộ Tài chính)" },
        { id: "151", name: "Đầu tư(Bộ Tài chính)" },
        { id: "15602", name: "Đầu tư(Bộ Tài chính)" },
        { id: "55", name: "Đầu tư bằng vốn hỗ trợ phát triển chính thức (ODA) và viện trợ không hoàn lại không thuộc hỗ trợ phát triển chính thức(Bộ Tài chính)" },
        { id: "58", name: "Đầu tư từ Việt nam ra nước ngoài(Bộ Tài chính)" },
        { id: "14262", name: "Đầu tư theo phương thức đối tác công tư(Bộ Tài chính)" },
        { id: "15082", name: "Đầu tư theo phương thức đối tác công tư (PPP)(Bộ Tài chính)" },
        { id: "57", name: "Đầu tư tại Việt nam(Bộ Tài chính)" },
        { id: "59", name: "Đầu tư vào nông nghiệp, nông thôn(Bộ Tài chính)" },
        { id: "50", name: "Đường bộ(Bộ Xây dựng)" },
        { id: "51", name: "Đường sắt(Bộ Xây dựng)" },
        { id: "218", name: "Gia đình(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14362", name: "Giám định thương mại(Bộ Công Thương)" },
        { id: "14402", name: "Giám định tư pháp(Bộ Xây dựng)" },
        { id: "202", name: "Giám định tư pháp(Bộ Tư pháp)" },
        { id: "250", name: "Giám định y khoa(Bộ Y tế)" },
        { id: "40", name: "Giáo dục dân tộc(Bộ Giáo dục và Đào tạo)" },
        { id: "37", name: "Giáo dục, đào tạo với nước ngoài(Bộ Giáo dục và Đào tạo)" },
        { id: "39", name: "Giáo dục đại học(Bộ Giáo dục và Đào tạo)" },
        { id: "41", name: "Giáo dục mầm non(Bộ Giáo dục và Đào tạo)" },
        { id: "38", name: "Giáo dục nghề nghiệp(Bộ Giáo dục và Đào tạo)" },
        { id: "77", name: "Giáo dục nghề nghiệp (G07-LĐ06)(Bộ Giáo dục và Đào tạo)" },
        { id: "42", name: "Giáo dục quốc phòng và an ninh(Bộ Giáo dục và Đào tạo)" },
        { id: "16242", name: "Giáo dục quốc phòng và an ninh(Bộ Quốc phòng)" },
        { id: "43", name: "Giáo dục thường xuyên(Bộ Giáo dục và Đào tạo)" },
        { id: "44", name: "Giáo dục tiểu học(Bộ Giáo dục và Đào tạo)" },
        { id: "45", name: "Giáo dục trung học(Bộ Giáo dục và Đào tạo)" },
        { id: "46", name: "Giáo dục và Đào tạo thuộc hệ thống giáo dục quốc dân(Bộ Giáo dục và Đào tạo)" },
        { id: "13853", name: "Giao thông vận tải(Bộ Xây dựng)" },
        { id: "268", name: "Giải quyết khiếu nại(Thanh tra Chính phủ)" },
        { id: "14502", name: "Giải quyết tố cáo(Bộ Quốc phòng)" },
        { id: "269", name: "Giải quyết tố cáo(Thanh tra Chính phủ)" },
        { id: "15542", name: "Giảm nghèo(Bộ Nông nghiệp và Môi trường)" },
        { id: "203", name: "Hộ tịch(Bộ Tư pháp)" },
        { id: "90", name: "Hộ tịch(Bộ Ngoại giao)" },
        { id: "14282", name: "Hộ tịch - Đăng ký, quản lý cư trú - Tài chính y tế(Bộ Tư pháp)" },
        { id: "14542", name: "Hộ tịch - Đăng ký thường trú - Bảo trợ xã hội - Người có công(Văn phòng Chính phủ)" },
        { id: "14562", name: "Hộ tịch - Đăng ký thường trú - Quản lý thu, Sổ - thẻ(Văn phòng Chính phủ)" },
        { id: "232", name: "Hạ tầng kỹ thuật(Bộ Xây dựng)" },
        { id: "233", name: "Hạ tầng kỹ thuật đô thị và khu công nghiệp, khu kinh tế và khu công nghệ cao(Bộ Xây dựng)" },
        { id: "60", name: "Hỗ trợ doanh nghiệp nhỏ và vừa(Bộ Tài chính)" },
        { id: "16462", name: "Hỗ trợ đầu tư(Bộ Tài chính)" },
        { id: "14050", name: "Hỗ trợ pháp lý cho doanh nghiệp nhỏ và vừa(Bộ Tư pháp)" },
        { id: "15362", name: "Hỗ trợ tổ hợp tác, hợp tác xã, liên hiệp hợp tác xã(Bộ Tài chính)" },
        { id: "53", name: "Hàng hải và đường thủy nội địa(Bộ Xây dựng)" },
        { id: "54", name: "Hàng không(Bộ Xây dựng)" },
        { id: "164", name: "Hành chính sự nghiệp(Bộ Tài chính)" },
        { id: "93", name: "Hồi hương(Bộ Ngoại giao)" },
        { id: "14202", name: "Hội nghị, hội thảo quốc tế(Bộ Ngoại giao)" },
        { id: "152", name: "Hải quan(Bộ Tài chính)" },
        { id: "21", name: "Hóa chất(Bộ Công Thương)" },
        { id: "204", name: "Hòa giải thương mại(Bộ Tư pháp)" },
        { id: "91", name: "Hoạt động của các tổ chức hợp tác, nghiên cứu song phương(Bộ Ngoại giao)" },
        { id: "92", name: "Hoạt động của các tổ chức phi chính phủ nước ngoài(Bộ Ngoại giao)" },
        { id: "264", name: "Hoạt động công nghệ thông tin ngân hàng(Ngân hàng Nhà nước Việt Nam)" },
        { id: "13706", name: "Hoạt động khác(Ngân hàng chính sách)" },
        { id: "266", name: "Hoạt động khác(Ngân hàng Nhà nước Việt Nam)" },
        { id: "263", name: "Hoạt động kho quỹ(Ngân hàng Nhà nước Việt Nam)" },
        { id: "68", name: "Hoạt động khoa học và công nghệ(Bộ Khoa học và Công nghệ)" },
        { id: "14101", name: "Hoạt động mua bán quốc tế chuyên ngành văn hóa(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "262", name: "Hoạt động ngoại hối(Ngân hàng Nhà nước Việt Nam)" },
        { id: "260", name: "Hoạt động thanh toán(Ngân hàng Nhà nước Việt Nam)" },
        { id: "265", name: "Hoạt động thông tin tín dụng(Ngân hàng Nhà nước Việt Nam)" },
        { id: "13705", name: "Hoạt động tín dụng(Ngân hàng chính sách)" },
        { id: "259", name: "Hoạt động tín dụng(Ngân hàng Nhà nước Việt Nam)" },
        { id: "261", name: "Hoạt động tiền tệ(Ngân hàng Nhà nước Việt Nam)" },
        { id: "241", name: "Hoạt động xây dựng(Bộ Xây dựng)" },
        { id: "101", name: "Hợp tác quốc tế(Bộ Nội vụ)" },
        { id: "234", name: "Hợp tác quốc tế(Bộ Xây dựng)" },
        { id: "169", name: "Hợp tác quốc tế(Bộ Tài chính)" },
        { id: "117", name: "Hợp tác quốc tế(Bộ Nông nghiệp và Môi trường)" },
        { id: "230", name: "Hợp tác quốc tế(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14806", name: "Hợp tác quốc tế về pháp luật(Bộ Tư pháp)" },
        { id: "153", name: "Kế hoạch - tài chính(Bộ Tài chính)" },
        { id: "112", name: "Kế hoạch - Tài chính(Bộ Nội vụ)" },
        { id: "15127", name: "Kỹ thuật an toàn và Môi trường công nghiệp(Bộ Công Thương)" },
        { id: "15182", name: "Kế toán(Bộ Tài chính)" },
        { id: "154", name: "Kế toán, kiểm toán(Bộ Tài chính)" },
        { id: "221", name: "Karaoke, Vũ trường(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "220", name: "Khách sạn(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "136", name: "Khám bệnh, chữa bệnh(Bộ Quốc phòng)" },
        { id: "252", name: "Khám bệnh, chữa bệnh(Bộ Y tế)" },
        { id: "16322", name: "Khen thưởng(Bộ Nội vụ)" },
        { id: "15243", name: "Khen thưởng(Thanh tra Chính phủ)" },
        { id: "148", name: "Khen thưởng(Bộ Quốc phòng)" },
        { id: "16006", name: "Khen thưởng đối ngoại(Bộ Ngoại giao)" },
        { id: "179", name: "Khí tượng, thủy văn(Bộ Nông nghiệp và Môi trường)" },
        { id: "146", name: "Khiếu nại(Bộ Quốc phòng)" },
        { id: "7", name: "Khiếu nại, tố cáo(Bộ Công an)" },
        { id: "155", name: "Kho bạc(Bộ Tài chính)" },
        { id: "16502", name: "Kho bạc nhà nước(Bộ Tài chính)" },
        { id: "13714", name: "Khoa học, công nghệ(Bộ Công Thương)" },
        { id: "16183", name: "Khoa học công nghệ(Bộ Tài chính)" },
        { id: "235", name: "Khoa học công nghệ và môi trường(Bộ Xây dựng)" },
        { id: "14949", name: "Khoa học quân sự(Bộ Quốc phòng)" },
        { id: "118", name: "Khoa học và Công nghệ(Bộ Nông nghiệp và Môi trường)" },
        { id: "16282", name: "Khoáng sản(Bộ Công Thương)" },
        { id: "14955", name: "Kiểm định an toàn kỹ thuật và bảo vệ môi trường của xe cơ giới, xe chuyên dùng(Bộ Công an)" },
        { id: "137", name: "Kiểm định an toàn lao động(Bộ Quốc phòng)" },
        { id: "14322", name: "Kiểm định chất lượng giáo dục(Bộ Giáo dục và Đào tạo)" },
        { id: "14742", name: "Kiểm định kỹ thuật an toàn lao động(Bộ Xây dựng)" },
        { id: "14662", name: "Kiểm lâm(Bộ Nông nghiệp và Môi trường)" },
        { id: "14682", name: "Kiểm ngư(Bộ Nông nghiệp và Môi trường)" },
        { id: "14842", name: "Kiểm soát thủ tục hành chính(Văn phòng Chính phủ)" },
        { id: "15582", name: "Kiểm tra kiến thức pháp luật về trật tự, an toàn giao thông đường bộ(Bộ Công an)" },
        { id: "236", name: "Kinh doanh bất động sản(Bộ Xây dựng)" },
        { id: "22", name: "Kinh doanh khí(Bộ Công Thương)" },
        { id: "119", name: "Kinh tế hợp tác và Phát triển nông thôn(Bộ Nông nghiệp và Môi trường)" },
        { id: "237", name: "Kinh tế xây dựng(Bộ Xây dựng)" },
        { id: "14963", name: "Kết hợp quốc phòng với kinh tế - xã hội(Bộ Quốc phòng)" },
        { id: "14970", name: "Ký kết, gia nhập điều ước quốc tế, thoả thuận quốc tế(Bộ Quốc phòng)" },
        { id: "219", name: "Lữ hành(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "222", name: "Lễ hội(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "78", name: "Lao động(Bộ Nội vụ)" },
        { id: "15962", name: "Lao động, Thương binh và Xã hội(Bộ Công Thương)" },
        { id: "16482", name: "Lao động, tiền lương(Bộ Nội vụ)" },
        { id: "15702", name: "Lao động, tiền lương, quan hệ lao động(Bộ Nội vụ)" },
        { id: "16262", name: "Lao động, tiền lương và bảo hiểm xã hội(Bộ Nội vụ)" },
        { id: "120", name: "Lâm nghiệp(Bộ Nông nghiệp và Môi trường)" },
        { id: "16103", name: "LĨNH VỰC CÔNG TÁC QUỐC PHÒNG Ở BỘ, NGÀNH TRUNG ƯƠNG, ĐỊA PHƯƠNG(Bộ Quốc phòng)" },
        { id: "191", name: "Lĩnh vực khác(Bộ Khoa học và Công nghệ)" },
        { id: "16162", name: "LĨNH VỰC KẾT HỢP QUỐC PHÒNG VỚI KINH TẾ - XÃ HỘI(Bộ Quốc phòng)" },
        { id: "16142", name: "LĨNH VỰC QUẢN LÝ HOẠT ĐỘNG KHẮC PHỤC HẬU QUẢ BOM MÌN VẬT NỔ SAU CHIẾN TRANH(Bộ Quốc phòng)" },
        { id: "205", name: "Luật sư(Bộ Tư pháp)" },
        { id: "23", name: "Lưu thông hàng hóa trong nước(Bộ Công Thương)" },
        { id: "15622", name: "Lý lịch tư pháp(Bộ Công an)" },
        { id: "253", name: "Mỹ phẩm(Bộ Y tế)" },
        { id: "223", name: "Mỹ thuật, nhiếp ảnh, triển lãm(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "95", name: "Miễn thị thực(Bộ Ngoại giao)" },
        { id: "182", name: "Môi trường(Bộ Nông nghiệp và Môi trường)" },
        { id: "13852", name: "Mật mã dân sự(Bộ Quốc phòng)" },
        { id: "24", name: "Năng lượng(Bộ Công Thương)" },
        { id: "15442", name: "Ứng phó sự cố tràn dầu(Bộ Quốc phòng)" },
        { id: "156", name: "Ngân sách Nhà nước(Bộ Tài chính)" },
        { id: "15222", name: "Nghề thủ công mỹ nghệ(Bộ Công Thương)" },
        { id: "224", name: "Nghệ thuật biểu diễn(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "138", name: "Nghĩa vụ quân sự(Bộ Quốc phòng)" },
        { id: "15142", name: "Nghiên cứu khoa học(Bộ Tài chính)" },
        { id: "80", name: "Người có công(Bộ Nội vụ)" },
        { id: "83", name: "Người lao động Việt Nam đi làm việc ở nước ngoài theo hợp đồng(Bộ Nội vụ)" },
        { id: "238", name: "Nhà ở và công sở(Bộ Xây dựng)" },
        { id: "16023", name: "Nội vụ(Bộ Ngoại giao)" },
        { id: "13759", name: "Nông nghiệp(Bộ Nông nghiệp và Môi trường)" },
        { id: "15802", name: "Nông nghiệp và Môi trường(Bộ Nông nghiệp và Môi trường)" },
        { id: "14783", name: "Nông thôn mới(Bộ Nông nghiệp và Môi trường)" },
        { id: "207", name: "Nuôi con nuôi(Bộ Tư pháp)" },
        { id: "208", name: "Phổ biến giáo dục pháp luật(Bộ Tư pháp)" },
        { id: "14803", name: "Phổ biến, giáo dục pháp luật (nội bộ)(Bộ Tư pháp)" },
        { id: "15422", name: "Pháp chế(Bộ Xây dựng)" },
        { id: "172", name: "Pháp chế(Bộ Tài chính)" },
        { id: "111", name: "Pháp chế(Bộ Nội vụ)" },
        { id: "14822", name: "Pháp điển hệ thống quy phạm pháp luật(Bộ Tư pháp)" },
        { id: "190", name: "Phát thanh, truyền hình và thông tin điện tử(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "16422", name: "Phát triển doanh nghiệp nhà nước(Bộ Tài chính)" },
        { id: "239", name: "Phát triển đô thị(Bộ Xây dựng)" },
        { id: "257", name: "Phòng bệnh(Bộ Y tế)" },
        { id: "8", name: "Phòng cháy, chữa cháy(Bộ Công an)" },
        { id: "81", name: "Phòng, chống tệ nạn xã hội(Bộ Y tế)" },
        { id: "267", name: "Phòng, chống tham nhũng(Thanh tra Chính phủ)" },
        { id: "15944", name: "Phòng chống tham nhũng(Bộ Công Thương)" },
        { id: "25", name: "Phòng vệ thương mại(Bộ Công Thương)" },
        { id: "14002", name: "QUÂN SỰ, QUỐC PHÒNG(Bộ Quốc phòng)" },
        { id: "168", name: "Quốc phòng, an ninh(Bộ Tài chính)" },
        { id: "14805", name: "Quốc tịch(Bộ Tư pháp)" },
        { id: "94", name: "Quốc tịch(Bộ Ngoại giao)" },
        { id: "210", name: "Quốc tịch(Bộ Tư pháp)" },
        { id: "14582", name: "Quản lý bán hàng đa cấp(Bộ Công Thương)" },
        { id: "139", name: "Quản lý biên giới(Bộ Quốc phòng)" },
        { id: "14945", name: "Quản lý biên giới(Bộ Quốc phòng)" },
        { id: "13712", name: "Quản lý bảo lãnh tín dụng của Nhà nước(Ngân hàng phát triển)" },
        { id: "231", name: "Quản lý chất lượng công trình xây dựng(Bộ Xây dựng)" },
        { id: "122", name: "Quản lý chất lượng nông lâm sản và thủy sản(Bộ Nông nghiệp và Môi trường)" },
        { id: "16582", name: "Quản lý chất lượng sản phẩm, hàng hoá(Bộ Công an)" },
        { id: "26", name: "Quản lý Cạnh tranh(Bộ Công Thương)" },
        { id: "143", name: "Quản lý công nghệ thông tin(Bộ Quốc phòng)" },
        { id: "157", name: "Quản lý công sản(Bộ Tài chính)" },
        { id: "14000", name: "Quản lý công trình quốc phòng, khu quân sự(Bộ Quốc phòng)" },
        { id: "240", name: "Quản lý doanh nghiệp(Bộ Xây dựng)" },
        { id: "123", name: "Quản lý doanh nghiệp(Bộ Nông nghiệp và Môi trường)" },
        { id: "121", name: "Quản lý Đê điều và Phòng, chống thiên tai(Bộ Nông nghiệp và Môi trường)" },
        { id: "15122", name: "Quản lý, điều hành chính sách điện năng(Bộ Công Thương)" },
        { id: "14964", name: "Quản lý đất quốc phòng(Bộ Quốc phòng)" },
        { id: "15023", name: "Quản lý đầu tư công(Bộ Tài chính)" },
        { id: "15022", name: "Quản lý đầu tư công (Vụ Tài chính - Kinh tế ngành)(Bộ Tài chính)" },
        { id: "15042", name: "Quản lý đầu tư công (Vụ Tổng hợp KTQD)(Bộ Tài chính)" },
        { id: "159", name: "Quản lý giá(Bộ Tài chính)" },
        { id: "14943", name: "Quản lý hoạt động khắc phục hậu quả bom mìn vật nổ sau chiến tranh(Bộ Quốc phòng)" },
        { id: "14004", name: "Quản lý hoạt động vật liệu nổ công nghiệp, tiền chất thuốc nổ(Bộ Quốc phòng)" },
        { id: "14944", name: "Quản lý khu kinh tế - quốc phòng(Bộ Quốc phòng)" },
        { id: "13752", name: "Quản lý lao động ngoài nước(Bộ Nội vụ)" },
        { id: "160", name: "Quản lý nợ(Bộ Tài chính)" },
        { id: "9", name: "Quản lý ngành nghề đầu tư, kinh doanh có điều kiện về an ninh, trật tự(Bộ Công an)" },
        { id: "13713", name: "Quản lý ngân sách nhà nước(Bộ Tài chính)" },
        { id: "15902", name: "quản lý ngoại thương(Bộ Công Thương)" },
        { id: "15084", name: "Quản lý nhà nước về hỗ trợ doanh nghiệp nhỏ và vừa(Bộ Tài chính)" },
        { id: "106", name: "Quản lý nhà nước về hội, quỹ(Bộ Nội vụ)" },
        { id: "15025", name: "Quản lý nhà nước về khu công nghiệp, khu kinh tế(Bộ Tài chính)" },
        { id: "16003", name: "Quản lý nhà nước về ký kết và thực hiện thoả thuận quốc tế(Bộ Ngoại giao)" },
        { id: "15762", name: "Quản lý nhà nước về thi đua, khen thưởng(Bộ Tư pháp)" },
        { id: "242", name: "Quản lý nhà và thị trường bất động sản(Bộ Xây dựng)" },
        { id: "13802", name: "Quản lý quỹ ngân sách, quỹ dự trữ nhà nước và các quỹ tài chính khác của Nhà nước(Bộ Tài chính)" },
        { id: "16204", name: "Quản lý, sử dụng vốn hỗ trợ phát triển chính thức (ODA) và vốn vay ưu đãi của nhà tài trợ nước ngoài(Bộ Tài chính)" },
        { id: "14200", name: "Quản lý sử dụng vũ khí, súng săn, vật liệu nổ, công cụ hỗ trợ(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14946", name: "Quản lý sĩ quan dự bị(Bộ Quốc phòng)" },
        { id: "15682", name: "Quản lý tài sản công(Bộ Tài chính)" },
        { id: "15128", name: "Quản lý thị trường(Bộ Công Thương)" },
        { id: "13701", name: "Quản lý thuế, phí, lệ phí và thu khác của ngân sách nhà nước(Bộ Tài chính)" },
        { id: "13710", name: "Quản lý Tín dụng của Nhà nước(Ngân hàng phát triển)" },
        { id: "13709", name: "Quản lý vốn uỷ thác(Ngân hàng phát triển)" },
        { id: "10", name: "Quản lý vũ khí, vật liệu nổ, công cụ hỗ trợ và pháo(Bộ Công an)" },
        { id: "140", name: "Quản lý vùng trời(Bộ Quốc phòng)" },
        { id: "124", name: "Quản lý xây dựng công trình(Bộ Nông nghiệp và Môi trường)" },
        { id: "14969", name: "Quản lý xúc tiến đầu tư(Bộ Quốc phòng)" },
        { id: "11", name: "Quản lý xuất nhập cảnh(Bộ Công an)" },
        { id: "209", name: "Quản tài viên(Bộ Tư pháp)" },
        { id: "15822", name: "Quản trị - Văn phòng(Bộ Y tế)" },
        { id: "226", name: "Quảng cáo(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "243", name: "Quy  hoạch  đô thị  và  nông  thôn, kiến trúc(Bộ Xây dựng)" },
        { id: "15102", name: "Quy chế làm việc(Văn phòng Chính phủ)" },
        { id: "15302", name: "Quy hoạch(Bộ Tài chính)" },
        { id: "15024", name: "Quy hoạch (Quản lý quy hoạch)(Bộ Tài chính)" },
        { id: "27", name: "Sở giao dịch hàng hóa(Bộ Công Thương)" },
        { id: "69", name: "Sở hữu trí tuệ(Bộ Khoa học và Công nghệ)" },
        { id: "15623", name: "Sát hạch, cấp giấy phép lái xe(Bộ Công an)" },
        { id: "15782", name: "Sản xuất, lắp ráp ô tô(Bộ Công Thương)" },
        { id: "107", name: "Tổ chức - Biên chế(Bộ Nội vụ)" },
        { id: "15003", name: "Tổ chức bộ máy(Bộ Nội vụ)" },
        { id: "16022", name: "Tổ chức bộ máy(Bộ Ngoại giao)" },
        { id: "15763", name: "Tổ chức bộ máy(Bộ Tư pháp)" },
        { id: "15624", name: "Tổ chức cai nghiên ma túy và quản lý sau cai nghiện(Bộ Công an)" },
        { id: "12", name: "Tổ chức, cán bộ(Bộ Công an)" },
        { id: "13704", name: "Tổ chức cán bộ(Ngân hàng chính sách)" },
        { id: "15242", name: "Tổ chức cán bộ(Thanh tra Chính phủ)" },
        { id: "255", name: "Tổ chức cán bộ(Bộ Y tế)" },
        { id: "170", name: "Tổ chức cán bộ(Bộ Tài chính)" },
        { id: "13950", name: "Tổ chức cán bộ(Bộ Nội vụ)" },
        { id: "105", name: "Tổ chức cán bộ(Bộ Nội vụ)" },
        { id: "15043", name: "Tổ chức cán bộ/Đào tạo, bồi dưỡng/Thi đua khen thưởng/Sáng kiến(Bộ Tài chính)" },
        { id: "14922", name: "Tài chính - Kế toán(Bộ Nội vụ)" },
        { id: "16182", name: "Tài chính - Kinh tế ngành(Bộ Tài chính)" },
        { id: "163", name: "Tài chính doanh nghiệp(Bộ Tài chính)" },
        { id: "15522", name: "Tài chính đất đai(Bộ Tài chính)" },
        { id: "165", name: "Tài chính ngân hàng(Bộ Tài chính)" },
        { id: "254", name: "Tài chính y tế(Bộ Y tế)" },
        { id: "183", name: "Tài nguyên nước(Bộ Nông nghiệp và Môi trường)" },
        { id: "15322", name: "Tài sản kết cấu hạ tầng chợ do Nhà nước đầu tư, quản lý(Bộ Công Thương)" },
        { id: "15162", name: "Tài vụ - nội bộ(Bộ Tài chính)" },
        { id: "15402", name: "test3(Bảo hiểm xã hội)" },
        { id: "228", name: "Thể dục thể thao(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14222", name: "Thừa phát lại(Bộ Tư pháp)" },
        { id: "61", name: "Thành lập và hoạt động của doanh nghiệp(Bộ Tài chính)" },
        { id: "62", name: "Thành lập và hoạt động của hợp tác xã(Bộ Tài chính)" },
        { id: "66", name: "Thành lập và hoạt động của quỹ đầu tư khởi nghiệp sáng tạo(Bộ Tài chính)" },
        { id: "14150", name: "Thành lập và hoạt động của tổ hợp tác(Bộ Tài chính)" },
        { id: "63", name: "Thành lập và hoạt động của tổ hợp tác, hợp tác xã, liên hiệp hợp tác xã(Bộ Tài chính)" },
        { id: "64", name: "Thành lập và hoạt động doanh nghiệp (hộ kinh doanh)(Bộ Tài chính)" },
        { id: "65", name: "Thành lập và hoạt động doanh nghiệp xã hội(Bộ Tài chính)" },
        { id: "258", name: "Thành lập và hoạt động ngân hàng(Ngân hàng Nhà nước Việt Nam)" },
        { id: "14482", name: "Thành lập và sắp xếp lại doanh nghiệp do Nhà nước nắm giữ 100 phần trăm vốn điều lệ(Bộ Tài chính)" },
        { id: "16423", name: "Thanh toán chi phí tố tụng(Bộ Tài chính)" },
        { id: "15742", name: "Thanh tra(Bộ Y tế)" },
        { id: "171", name: "Thanh tra(Bộ Tài chính)" },
        { id: "15482", name: "Thanh tra(Thanh tra Chính phủ)" },
        { id: "102", name: "Thanh tra Bộ(Bộ Nội vụ)" },
        { id: "13761", name: "Thực hiện chính sách BHXH(Bộ Tài chính)" },
        { id: "13800", name: "Thực hiện chính sách BHYT(Bộ Tài chính)" },
        { id: "161", name: "Thi đua - khen thưởng(Bộ Tài chính)" },
        { id: "103", name: "Thi đua - khen thưởng(Bộ Nội vụ)" },
        { id: "229", name: "Thi đua – Khen thưởng(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14902", name: "Thi đua - Khen thưởng(Bộ Nội vụ)" },
        { id: "14303", name: "Thi đua, khen thưởng(Bộ Y tế)" },
        { id: "28", name: "Thi đua, khen thưởng(Bộ Công Thương)" },
        { id: "14903", name: "Thi đua khen thưởng(Bộ Nông nghiệp và Môi trường)" },
        { id: "211", name: "Thi hành án dân sự(Bộ Tư pháp)" },
        { id: "14804", name: "Thi hành án dân sự(Bộ Tư pháp)" },
        { id: "14966", name: "Thi hành án dân sự(Bộ Quốc phòng)" },
        { id: "245", name: "Thí nghiệm chuyên ngành xây dựng(Bộ Xây dựng)" },
        { id: "47", name: "Thi, tuyển sinh(Bộ Giáo dục và Đào tạo)" },
        { id: "256", name: "Thiết bị y tế(Bộ Y tế)" },
        { id: "14762", name: "Thông tin báo chí(Bộ Tư pháp)" },
        { id: "193", name: "Thông tin cơ sở(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "194", name: "Thông tin đối ngoại(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "15982", name: "Thông tin liên lạc quân sự(Bộ Quốc phòng)" },
        { id: "15943", name: "Thông tin và Truyền thông(Bộ Công Thương)" },
        { id: "16105", name: "Thông tin và Truyền thông(Bộ Y tế)" },
        { id: "166", name: "Thuế(Bộ Tài chính)" },
        { id: "13763", name: "Thu BHXH, BHYT, BHTN, BH tai nạn lao động, BNN(Bộ Tài chính)" },
        { id: "125", name: "Thú y(Bộ Nông nghiệp và Môi trường)" },
        { id: "225", name: "Thư viện(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "29", name: "Thương mại biên giới và miền núi(Bộ Công Thương)" },
        { id: "30", name: "Thương mại điện tử(Bộ Công Thương)" },
        { id: "31", name: "Thương mại quốc tế(Bộ Công Thương)" },
        { id: "126", name: "Thủy lợi(Bộ Nông nghiệp và Môi trường)" },
        { id: "127", name: "Thủy sản(Bộ Nông nghiệp và Môi trường)" },
        { id: "70", name: "Tiêu chuẩn đo lường chất lượng(Bộ Khoa học và Công nghệ)" },
        { id: "32", name: "Tiêu chuẩn đo lường chất lượng(Bộ Công Thương)" },
        { id: "48", name: "Tiêu chuẩn nhà giáo, cán bộ quản lý giáo dục(Bộ Giáo dục và Đào tạo)" },
        { id: "167", name: "Tin học - Thống kê(Bộ Tài chính)" },
        { id: "79", name: "Tiền lương(Bộ Nội vụ)" },
        { id: "104", name: "Tiền lương(Bộ Nội vụ)" },
        { id: "108", name: "Tín ngưỡng, tôn giáo(Dân tộc và Tôn giáo)" },
        { id: "270", name: "Tiếp công dân(Thanh tra Chính phủ)" },
        { id: "15125", name: "Tiết kiệm năng lượng(Bộ Công Thương)" },
        { id: "192", name: "Tần số vô tuyến điện(Bộ Khoa học và Công nghệ)" },
        { id: "109", name: "Tổng hợp(Bộ Nội vụ)" },
        { id: "184", name: "Tổng hợp(Bộ Nông nghiệp và Môi trường)" },
        { id: "14242", name: "Tòa án(Toàn án nhân dân tối cao)" },
        { id: "16223", name: "Trẻ em(Bộ Y tế)" },
        { id: "212", name: "Trợ giúp pháp lý(Bộ Tư pháp)" },
        { id: "213", name: "Trọng tài thương mại(Bộ Tư pháp)" },
        { id: "128", name: "Trồng trọt(Bộ Nông nghiệp và Môi trường)" },
        { id: "114", name: "Trồng trọt và Bảo vệ thực vật(Bộ Nông nghiệp và Môi trường)" },
        { id: "14722", name: "TTHCNOIBO-Chế độ chính sách cán bộ (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14727", name: "TTHCNOIBO-Chuyển đổi số quốc gia và Chính phủ số (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14712", name: "TTHCNOIBO-Đào tạo, bồi dưỡng (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14726", name: "TTHCNOIBO-Đoàn ra (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14705", name: "TTHCNOIBO-Hợp tác quốc tế (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14725", name: "TTHCNOIBO-Kế hoạch - Tài chính (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "13702", name: "TTHCNOIBO-Khoa học và Công nghệ (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14707", name: "TTHCNOIBO-Kiểm soát thủ tục hành chính (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14709", name: "TTHCNOIBO-Lưu trữ (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14703", name: "TTHCNOIBO-Nhân sự (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14724", name: "TTHCNOIBO-Pháp chế (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14711", name: "TTHCNOIBO-Quản lý tài sản (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14704", name: "TTHCNOIBO-Tổ chức (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14723", name: "TTHCNOIBO-Thi đua - Khen thưởng (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14702", name: "TTHCNOIBO-Thông tin, tuyên truyền (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14710", name: "TTHCNOIBO-Tổng hợp (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14708", name: "TTHCNOIBO-Văn thư (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "141", name: "Tuyển sinh quân sự(Bộ Quốc phòng)" },
        { id: "14782", name: "Tư pháp(Bộ Tư pháp)" },
        { id: "214", name: "Tư vấn pháp luật(Bộ Tư pháp)" },
        { id: "14642", name: "Ưu đãi, miễn trừ(Bộ Ngoại giao)" },
        { id: "15083", name: "v(Bộ Kế hoạch và Đầu tư)" },
        { id: "13758", name: "Văn bằng, chứng chỉ(Bộ Giáo dục và Đào tạo)" },
        { id: "227", name: "Văn hóa(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "16122", name: "Văn phòng(Bộ Y tế)" },
        { id: "173", name: "Văn phòng(Bộ Tài chính)" },
        { id: "113", name: "Văn phòng(Bộ Nội vụ)" },
        { id: "110", name: "Văn thư và Lưu trữ nhà nước(Bộ Nội vụ)" },
        { id: "82", name: "Việc làm(Bộ Nội vụ)" },
        { id: "15304", name: "Viện Nghiên cứu Quản lý kinh tế Trung ương(Bộ Kế hoạch và Đầu tư)" },
        { id: "185", name: "Viễn thám(Bộ Nông nghiệp và Môi trường)" },
        { id: "195", name: "Viễn thông và Internet(Bộ Khoa học và Công nghệ)" },
        { id: "15062", name: "Viện trợ không hoàn lại không thuộc hỗ trợ phát triển chính thức của các cơ quan, tổ chức, cá nhân nước ngoài dành cho Việt Nam(Bộ Tài chính)" },
        { id: "16342", name: "Vận chuyển hàng hóa nguy hiểm(Bộ Công Thương)" },
        { id: "33", name: "Vật liệu nổ công nghiệp, tiền chất thuốc nổ(Bộ Công Thương)" },
        { id: "244", name: "Vật liệu xây dựng(Bộ Xây dựng)" },
        { id: "271", name: "Xử lý đơn thư(Thanh tra Chính phủ)" },
        { id: "15942", name: "Xử lý vi phạm hành chính(Bộ Công Thương)" },
        { id: "15922", name: "Xây dựng, ban hành văn bản QPPL(Bộ Công Thương)" },
        { id: "16024", name: "Xây dựng ngành(Bộ Ngoại giao)" },
        { id: "15743", name: "Xây dựng pháp luật(Bộ Y tế)" },
        { id: "14802", name: "Xây dựng pháp luật(Bộ Tư pháp)" },
        { id: "15002", name: "Xây dựng văn bản quy phạm pháp luật(Bộ Tư pháp)" },
        { id: "142", name: "Xe - máy quân sự(Bộ Quốc phòng)" },
        { id: "16082", name: "Xe - máy quân sự(Bộ Quốc phòng)" },
        { id: "35", name: "Xúc tiến thương mại(Bộ Công Thương)" },
        { id: "196", name: "Xuất Bản, In và Phát hành(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "34", name: "Xuất nhập khẩu(Bộ Công Thương)" },
        { id: "13803", name: "Xuất nhập khẩu văn hóa phẩm không nhằm mục đích kinh doanh(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14302", name: "Y Dược cổ truyền(Bộ Y tế)" },
    ],
    implementationLevels: [
        { id: "1", name: "Cấp Trung ương" },
        { id: "2", name: "Cấp Bộ" },
        { id: "3", name: "Cấp Ban" },
        { id: "4", name: "Cấp Ngành" },
    ],
    targetAudiences: [
        { id: "4", name: "Cán bộ, công chức, viên chức" },
        { id: "1", name: "Công dân Việt Nam" },
        { id: "5", name: "Doanh nghiệp" },
        { id: "6", name: "Doanh nghiệp có vốn đầu tư nước ngoài" },
        { id: "9", name: "Hợp tác xã" },
        { id: "3", name: "Người nước ngoài" },
        { id: "2", name: "Người Việt Nam định cư ở nước ngoài" },
        { id: "7", name: "Tổ chức (không bao gồm doanh nghiệp, HTX)" },
        { id: "8", name: "Tổ chức nước ngoài" },
    ],
};

/**
 * Filter options for "Tỉnh/Thành phố" (Province) search
 * Data from API: Implementing Agencies (Cơ quan thực hiện)
 */
export const PROVINCE_FILTER_OPTIONS: FilterOptions = {
    implementingAgencies: [
        { id: "409587", name: "UBND Thành phố Cần Thơ" },
        { id: "426100", name: "UBND Thành phố Đà Nẵng" },
        { id: "411312", name: "UBND Thành phố Hồ Chí Minh" },
        { id: "389181", name: "UBND Thành phố Hà Nội" },
        { id: "387628", name: "UBND Thành phố Hải Phòng" },
        { id: "374087", name: "UBND Thành phố Huế" },
        { id: "398126", name: "UBND tỉnh An Giang" },
        { id: "401621", name: "UBND tỉnh Bắc Ninh" },
        { id: "408562", name: "UBND tỉnh Cà Mau" },
        { id: "410516", name: "UBND tỉnh Cao Bằng" },
        { id: "383348", name: "UBND tỉnh Điện Biên" },
        { id: "381137", name: "UBND tỉnh Đắk Lắk" },
        { id: "426101", name: "UBND tỉnh Đồng Nai" },
        { id: "374613", name: "UBND tỉnh Đồng Tháp" },
        { id: "384251", name: "UBND tỉnh Gia Lai" },
        { id: "390693", name: "UBND tỉnh Hà Tĩnh" },
        { id: "426108", name: "UBND tỉnh Hưng Yên" },
        { id: "415139", name: "UBND tỉnh Khánh Hòa" },
        { id: "420192", name: "UBND tỉnh Lai Châu" },
        { id: "426105", name: "UBND tỉnh Lào Cai" },
        { id: "421149", name: "UBND tỉnh Lâm Đồng" },
        { id: "417489", name: "UBND tỉnh Lạng Sơn" },
        { id: "418979", name: "UBND tỉnh Nghệ An" },
        { id: "393975", name: "UBND tỉnh Ninh Bình" },
        { id: "422607", name: "UBND tỉnh Phú Thọ" },
        { id: "365792", name: "UBND tỉnh Quảng Ngãi" },
        { id: "426106", name: "UBND tỉnh Quảng Ninh" },
        { id: "6715", name: "UBND tỉnh Quảng Trị" },
        { id: "426103", name: "UBND tỉnh Sơn La" },
        { id: "369810", name: "UBND tỉnh Tây Ninh" },
        { id: "370865", name: "UBND tỉnh Thái Nguyên" },
        { id: "371854", name: "UBND tỉnh Thanh Hóa" },
        { id: "384979", name: "UBND tỉnh Tuyên Quang" },
        { id: "377087", name: "UBND tỉnh Vĩnh Long" },
    ],
    fields: [
        { id: "67", name: "An toàn bức xạ và hạt nhân(Bộ Khoa học và Công nghệ)" },
        { id: "13754", name: "An toàn đập, hồ chứa thuỷ điện(Bộ Công Thương)" },
        { id: "14422", name: "An toàn lao động trong thi công xây dựng công trình(Bộ Xây dựng)" },
        { id: "13", name: "An toàn thực phẩm(Bộ Công Thương)" },
        { id: "246", name: "An toàn thực phẩm(Bộ Y tế)" },
        { id: "72", name: "An toàn, vệ sinh lao động(Bộ Nội vụ)" },
        { id: "14", name: "An toàn vệ sinh lao động(Bộ Công Thương)" },
        { id: "16062", name: "An toàn vệ sinh lao động(Bộ Quốc phòng)" },
        { id: "15143", name: "Bộ Tài chính(Bộ Tài chính)" },
        { id: "187", name: "Báo chí(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "145", name: "Báo chí(Bộ Quốc phòng)" },
        { id: "84", name: "Báo chí(Bộ Ngoại giao)" },
        { id: "16042", name: "Bậc kỹ thuật nghề(Bộ Quốc phòng)" },
        { id: "198", name: "Bồi thường nhà nước(Bộ Tư pháp)" },
        { id: "16025", name: "Biên giới lãnh thổ(Bộ Ngoại giao)" },
        { id: "180", name: "Biến đổi khí hậu(Bộ Nông nghiệp và Môi trường)" },
        { id: "174", name: "Biển và hải đảo(Bộ Nông nghiệp và Môi trường)" },
        { id: "76", name: "Bình đẳng giới(Bộ Nội vụ)" },
        { id: "215", name: "Bản quyền tác giả(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "15662", name: "Bảo đảm an ninh hàng không(Bộ Công an)" },
        { id: "15842", name: "Bảo đảm trật tự, an toàn giao thông đường bộ(Bộ Công an)" },
        { id: "162", name: "Bảo hiểm(Bộ Tài chính)" },
        { id: "16522", name: "Bảo hiểm xã hội(Bộ Tài chính)" },
        { id: "73", name: "Bảo hiểm xã hội(Bộ Nội vụ)" },
        { id: "16382", name: "Bảo hiểm y tế(Bộ Y tế)" },
        { id: "14602", name: "Bảo tồn thiên nhiên và Đa dạng sinh học(Bộ Nông nghiệp và Môi trường)" },
        { id: "74", name: "Bảo trợ xã hội(Bộ Y tế)" },
        { id: "16104", name: "Bảo vệ Bí mật nhà nước(Bộ Y tế)" },
        { id: "13851", name: "Bảo vệ công trình quốc phòng và khu quân sự(Bộ Quốc phòng)" },
        { id: "14622", name: "Bảo vệ dữ liệu cá nhân(Bộ Công an)" },
        { id: "15882", name: "Bảo vệ môi trường ngành Công Thương(Bộ Công Thương)" },
        { id: "15262", name: "bảo vệ quyền lợi người tiêu dùng(Bộ Công Thương)" },
        { id: "14968", name: "Bảo vệ vành đai an toàn kho đạn dược(Bộ Quốc phòng)" },
        { id: "188", name: "Bưu chính(Bộ Khoa học và Công nghệ)" },
        { id: "13854", name: "Các cơ sở giáo dục khác(Bộ Giáo dục và Đào tạo)" },
        { id: "13902", name: "Các dịch vụ hỗ trợ(Điện Lực)" },
        { id: "13711", name: "Các hoạt động khác của NHPT(Ngân hàng phát triển)" },
        { id: "116", name: "Chế biến và phát triển thị trường Nông sản(Bộ Nông nghiệp và Môi trường)" },
        { id: "16542", name: "Chế độ, chính sách đối với nhà giáo(Bộ Giáo dục và Đào tạo)" },
        { id: "115", name: "Chăn nuôi(Bộ Nông nghiệp và Môi trường)" },
        { id: "13762", name: "Chi trả các chế độ BHXH(Bộ Tài chính)" },
        { id: "97", name: "Chính quyền địa phương(Bộ Nội vụ)" },
        { id: "3", name: "Chính sách(Bộ Công an)" },
        { id: "131", name: "Chính sách(Bộ Quốc phòng)" },
        { id: "149", name: "Chính sách Thuế(Bộ Tài chính)" },
        { id: "150", name: "Chứng khoán(Bộ Tài chính)" },
        { id: "15562", name: "Chứng nhận chất lượng an toàn kỹ thuật và bảo vệ môi trường(Bộ Công an)" },
        { id: "86", name: "Chứng nhận lãnh sự, hợp pháp hóa lãnh sự(Bộ Ngoại giao)" },
        { id: "14442", name: "Chứng nhận xuất trình(Bộ Ngoại giao)" },
        { id: "199", name: "Chứng thực(Bộ Tư pháp)" },
        { id: "132", name: "Chứng thực điện tử(Bộ Quốc phòng)" },
        { id: "16362", name: "chất lượng sản phẩm hàng hóa(Bộ Công Thương)" },
        { id: "16562", name: "Chuẩn tiếp cận pháp luật(Bộ Tư pháp)" },
        { id: "15342", name: "Chuyển đổi công ty nhà nước được thành lập và hoạt động theo Luật Doanh nghiệp nhà nước thành công ty trách nhiệm hữu hạn một thành viên tổ chức và hoạt động theo quy định tại Luật Doanh nghiệp(Bộ Tài chính)" },
        { id: "14947", name: "Chuyển nhượng vốn(Bộ Quốc phòng)" },
        { id: "96", name: "Cải cách hành chính(Bộ Nội vụ)" },
        { id: "15202", name: "Cụm Công nghiệp(Bộ Công Thương)" },
        { id: "98", name: "Công chức, viên chức(Bộ Nội vụ)" },
        { id: "200", name: "Công chứng(Bộ Tư pháp)" },
        { id: "87", name: "Công chứng, chứng thực(Bộ Ngoại giao)" },
        { id: "15764", name: "Công chứng (nội bộ)(Bộ Tư pháp)" },
        { id: "14967", name: "Công nghệ thông tin(Bộ Quốc phòng)" },
        { id: "189", name: "Công nghệ thông tin, điện tử(Bộ Khoa học và Công nghệ)" },
        { id: "15282", name: "Công nghệ thông tin và chuyển đổi số(Bộ Tài chính)" },
        { id: "15", name: "Công nghiệp địa phương(Bộ Công Thương)" },
        { id: "16", name: "Công nghiệp nặng(Bộ Công Thương)" },
        { id: "16402", name: "Công nghiệp quốc phòng, an ninh(Bộ Quốc phòng)" },
        { id: "17", name: "Công nghiệp tiêu dùng(Bộ Công Thương)" },
        { id: "15123", name: "Công tác cán bộ(Bộ Công Thương)" },
        { id: "16004", name: "Công tác cán bộ(Bộ Ngoại giao)" },
        { id: "272", name: "Công tác dân tộc(Dân tộc và Tôn giáo)" },
        { id: "16302", name: "Công tác dân tộc, tín ngưỡng, tôn giáo(Dân tộc và Tôn giáo)" },
        { id: "13700", name: "Công tác lãnh sự(Bộ Ngoại giao)" },
        { id: "15124", name: "Công tác pháp chế(Bộ Công Thương)" },
        { id: "14942", name: "Công tác quân sự quốc phòng(Bộ Quốc phòng)" },
        { id: "99", name: "Công tác thanh niên(Bộ Nội vụ)" },
        { id: "15502", name: "Công tác văn phòng(Bộ Công Thương)" },
        { id: "14862", name: "Công tác Văn phòng(Văn phòng Chính phủ)" },
        { id: "14965", name: "Công tác văn phòng(Bộ Quốc phòng)" },
        { id: "15126", name: "Công Thương địa phương(Bộ Công Thương)" },
        { id: "36", name: "Cơ sở vật chất và thiết bị trường học(Bộ Giáo dục và Đào tạo)" },
        { id: "133", name: "Cơ yếu(Bộ Quốc phòng)" },
        { id: "85", name: "Cấp hộ chiếu, giấy thông hành, công hàm đề nghị cấp thị thực(Bộ Ngoại giao)" },
        { id: "1", name: "Cấp, quản lý căn cước(Bộ Công an)" },
        { id: "13760", name: "Cấp sổ BHXH, thẻ BHYT(Bộ Tài chính)" },
        { id: "88", name: "Cấp thị thực, gia hạn tạm trú(Bộ Ngoại giao)" },
        { id: "14948", name: "Cung cấp thông tin về liệt sĩ, mộ liệt sĩ(Bộ Quốc phòng)" },
        { id: "16442", name: "Dữ liệu(Bộ Công an)" },
        { id: "158", name: "Dự trữ(Bộ Tài chính)" },
        { id: "16202", name: "Dự trữ nhà nước(Bộ Tài chính)" },
        { id: "134", name: "Dân quân tự vệ(Bộ Quốc phòng)" },
        { id: "247", name: "Dân số, Bà mẹ - Trẻ em(Bộ Y tế)" },
        { id: "15862", name: "Dịch vụ công trong Đảng(Văn phòng Trung ương Đảng)" },
        { id: "13900", name: "Dịch vụ cung cấp điện mới(Điện Lực)" },
        { id: "14100", name: "Dịch vụ du lịch khác(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "16203", name: "Dịch vụ tài chính(Bộ Tài chính)" },
        { id: "19", name: "Dịch vụ thương mại(Bộ Công Thương)" },
        { id: "13901", name: "Dịch vụ trong quá trình thực hiện HĐMBĐ(Điện Lực)" },
        { id: "216", name: "Di sản văn hóa(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "16043", name: "Doanh trại(Bộ Quốc phòng)" },
        { id: "18", name: "Dầu khí(Bộ Công Thương)" },
        { id: "15583", name: "dầu khí(Bộ Công Thương)" },
        { id: "14382", name: "Du lịch(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "249", name: "Dược phẩm(Bộ Y tế)" },
        { id: "16005", name: "Đào tạo bồi dưỡng(Bộ Ngoại giao)" },
        { id: "100", name: "Đào tạo, bồi dưỡng cán bộ công chức, viên chức(Bộ Nội vụ)" },
        { id: "248", name: "Đào tạo và Nghiên cứu khoa học(Bộ Y tế)" },
        { id: "49", name: "Đăng kiểm(Bộ Xây dựng)" },
        { id: "201", name: "Đăng ký biện pháp bảo đảm(Bộ Tư pháp)" },
        { id: "89", name: "Đăng ký công dân(Bộ Ngoại giao)" },
        { id: "4", name: "Đăng ký, quản lý con dấu(Bộ Công an)" },
        { id: "5", name: "Đăng ký, quản lý cư trú(Bộ Công an)" },
        { id: "6", name: "Đăng ký, quản lý phương tiện giao thông cơ giới, xe máy chuyên dùng(Bộ Công an)" },
        { id: "16002", name: "Đối ngoại(Bộ Ngoại giao)" },
        { id: "144", name: "Đối ngoại quốc phòng(Bộ Quốc phòng)" },
        { id: "176", name: "Địa chất và khoáng sản(Bộ Nông nghiệp và Môi trường)" },
        { id: "20", name: "Điện(Bộ Công Thương)" },
        { id: "15462", name: "Điện lực(Bộ Công Thương)" },
        { id: "217", name: "Điện ảnh(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "15642", name: "Đảm bảo an toàn thông tin, an ninh mạng(Bộ Công an)" },
        { id: "14962", name: "Động viên công nghiệp(Bộ Quốc phòng)" },
        { id: "135", name: "Động viên quân đội(Bộ Quốc phòng)" },
        { id: "14522", name: "Định danh và xác thực điện tử(Bộ Công an)" },
        { id: "177", name: "Đo đạc, bản đồ và thông tin địa lý(Bộ Nông nghiệp và Môi trường)" },
        { id: "175", name: "Đất đai(Bộ Nông nghiệp và Môi trường)" },
        { id: "197", name: "Đấu giá tài sản(Bộ Tư pháp)" },
        { id: "56", name: "Đấu thầu(Bộ Tài chính)" },
        { id: "13708", name: "Đấu thầu lựa chọn nhà đầu tư(Bộ Tài chính)" },
        { id: "151", name: "Đầu tư(Bộ Tài chính)" },
        { id: "15602", name: "Đầu tư(Bộ Tài chính)" },
        { id: "55", name: "Đầu tư bằng vốn hỗ trợ phát triển chính thức (ODA) và viện trợ không hoàn lại không thuộc hỗ trợ phát triển chính thức(Bộ Tài chính)" },
        { id: "58", name: "Đầu tư từ Việt nam ra nước ngoài(Bộ Tài chính)" },
        { id: "14262", name: "Đầu tư theo phương thức đối tác công tư(Bộ Tài chính)" },
        { id: "15082", name: "Đầu tư theo phương thức đối tác công tư (PPP)(Bộ Tài chính)" },
        { id: "57", name: "Đầu tư tại Việt nam(Bộ Tài chính)" },
        { id: "59", name: "Đầu tư vào nông nghiệp, nông thôn(Bộ Tài chính)" },
        { id: "50", name: "Đường bộ(Bộ Xây dựng)" },
        { id: "51", name: "Đường sắt(Bộ Xây dựng)" },
        { id: "218", name: "Gia đình(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14362", name: "Giám định thương mại(Bộ Công Thương)" },
        { id: "14402", name: "Giám định tư pháp(Bộ Xây dựng)" },
        { id: "202", name: "Giám định tư pháp(Bộ Tư pháp)" },
        { id: "250", name: "Giám định y khoa(Bộ Y tế)" },
        { id: "40", name: "Giáo dục dân tộc(Bộ Giáo dục và Đào tạo)" },
        { id: "37", name: "Giáo dục, đào tạo với nước ngoài(Bộ Giáo dục và Đào tạo)" },
        { id: "39", name: "Giáo dục đại học(Bộ Giáo dục và Đào tạo)" },
        { id: "41", name: "Giáo dục mầm non(Bộ Giáo dục và Đào tạo)" },
        { id: "38", name: "Giáo dục nghề nghiệp(Bộ Giáo dục và Đào tạo)" },
        { id: "77", name: "Giáo dục nghề nghiệp (G07-LĐ06)(Bộ Giáo dục và Đào tạo)" },
        { id: "42", name: "Giáo dục quốc phòng và an ninh(Bộ Giáo dục và Đào tạo)" },
        { id: "16242", name: "Giáo dục quốc phòng và an ninh(Bộ Quốc phòng)" },
        { id: "43", name: "Giáo dục thường xuyên(Bộ Giáo dục và Đào tạo)" },
        { id: "44", name: "Giáo dục tiểu học(Bộ Giáo dục và Đào tạo)" },
        { id: "45", name: "Giáo dục trung học(Bộ Giáo dục và Đào tạo)" },
        { id: "46", name: "Giáo dục và Đào tạo thuộc hệ thống giáo dục quốc dân(Bộ Giáo dục và Đào tạo)" },
        { id: "13853", name: "Giao thông vận tải(Bộ Xây dựng)" },
        { id: "268", name: "Giải quyết khiếu nại(Thanh tra Chính phủ)" },
        { id: "14502", name: "Giải quyết tố cáo(Bộ Quốc phòng)" },
        { id: "269", name: "Giải quyết tố cáo(Thanh tra Chính phủ)" },
        { id: "15542", name: "Giảm nghèo(Bộ Nông nghiệp và Môi trường)" },
        { id: "203", name: "Hộ tịch(Bộ Tư pháp)" },
        { id: "90", name: "Hộ tịch(Bộ Ngoại giao)" },
        { id: "14282", name: "Hộ tịch - Đăng ký, quản lý cư trú - Tài chính y tế(Bộ Tư pháp)" },
        { id: "14542", name: "Hộ tịch - Đăng ký thường trú - Bảo trợ xã hội - Người có công(Văn phòng Chính phủ)" },
        { id: "14562", name: "Hộ tịch - Đăng ký thường trú - Quản lý thu, Sổ - thẻ(Văn phòng Chính phủ)" },
        { id: "232", name: "Hạ tầng kỹ thuật(Bộ Xây dựng)" },
        { id: "233", name: "Hạ tầng kỹ thuật đô thị và khu công nghiệp, khu kinh tế và khu công nghệ cao(Bộ Xây dựng)" },
        { id: "60", name: "Hỗ trợ doanh nghiệp nhỏ và vừa(Bộ Tài chính)" },
        { id: "16462", name: "Hỗ trợ đầu tư(Bộ Tài chính)" },
        { id: "14050", name: "Hỗ trợ pháp lý cho doanh nghiệp nhỏ và vừa(Bộ Tư pháp)" },
        { id: "15362", name: "Hỗ trợ tổ hợp tác, hợp tác xã, liên hiệp hợp tác xã(Bộ Tài chính)" },
        { id: "53", name: "Hàng hải và đường thủy nội địa(Bộ Xây dựng)" },
        { id: "54", name: "Hàng không(Bộ Xây dựng)" },
        { id: "164", name: "Hành chính sự nghiệp(Bộ Tài chính)" },
        { id: "93", name: "Hồi hương(Bộ Ngoại giao)" },
        { id: "14202", name: "Hội nghị, hội thảo quốc tế(Bộ Ngoại giao)" },
        { id: "152", name: "Hải quan(Bộ Tài chính)" },
        { id: "21", name: "Hóa chất(Bộ Công Thương)" },
        { id: "204", name: "Hòa giải thương mại(Bộ Tư pháp)" },
        { id: "91", name: "Hoạt động của các tổ chức hợp tác, nghiên cứu song phương(Bộ Ngoại giao)" },
        { id: "92", name: "Hoạt động của các tổ chức phi chính phủ nước ngoài(Bộ Ngoại giao)" },
        { id: "264", name: "Hoạt động công nghệ thông tin ngân hàng(Ngân hàng Nhà nước Việt Nam)" },
        { id: "13706", name: "Hoạt động khác(Ngân hàng chính sách)" },
        { id: "266", name: "Hoạt động khác(Ngân hàng Nhà nước Việt Nam)" },
        { id: "263", name: "Hoạt động kho quỹ(Ngân hàng Nhà nước Việt Nam)" },
        { id: "68", name: "Hoạt động khoa học và công nghệ(Bộ Khoa học và Công nghệ)" },
        { id: "14101", name: "Hoạt động mua bán quốc tế chuyên ngành văn hóa(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "262", name: "Hoạt động ngoại hối(Ngân hàng Nhà nước Việt Nam)" },
        { id: "260", name: "Hoạt động thanh toán(Ngân hàng Nhà nước Việt Nam)" },
        { id: "265", name: "Hoạt động thông tin tín dụng(Ngân hàng Nhà nước Việt Nam)" },
        { id: "13705", name: "Hoạt động tín dụng(Ngân hàng chính sách)" },
        { id: "259", name: "Hoạt động tín dụng(Ngân hàng Nhà nước Việt Nam)" },
        { id: "261", name: "Hoạt động tiền tệ(Ngân hàng Nhà nước Việt Nam)" },
        { id: "241", name: "Hoạt động xây dựng(Bộ Xây dựng)" },
        { id: "101", name: "Hợp tác quốc tế(Bộ Nội vụ)" },
        { id: "234", name: "Hợp tác quốc tế(Bộ Xây dựng)" },
        { id: "169", name: "Hợp tác quốc tế(Bộ Tài chính)" },
        { id: "117", name: "Hợp tác quốc tế(Bộ Nông nghiệp và Môi trường)" },
        { id: "230", name: "Hợp tác quốc tế(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14806", name: "Hợp tác quốc tế về pháp luật(Bộ Tư pháp)" },
        { id: "153", name: "Kế hoạch - tài chính(Bộ Tài chính)" },
        { id: "112", name: "Kế hoạch - Tài chính(Bộ Nội vụ)" },
        { id: "15127", name: "Kỹ thuật an toàn và Môi trường công nghiệp(Bộ Công Thương)" },
        { id: "15182", name: "Kế toán(Bộ Tài chính)" },
        { id: "154", name: "Kế toán, kiểm toán(Bộ Tài chính)" },
        { id: "221", name: "Karaoke, Vũ trường(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "220", name: "Khách sạn(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "136", name: "Khám bệnh, chữa bệnh(Bộ Quốc phòng)" },
        { id: "252", name: "Khám bệnh, chữa bệnh(Bộ Y tế)" },
        { id: "16322", name: "Khen thưởng(Bộ Nội vụ)" },
        { id: "15243", name: "Khen thưởng(Thanh tra Chính phủ)" },
        { id: "148", name: "Khen thưởng(Bộ Quốc phòng)" },
        { id: "16006", name: "Khen thưởng đối ngoại(Bộ Ngoại giao)" },
        { id: "179", name: "Khí tượng, thủy văn(Bộ Nông nghiệp và Môi trường)" },
        { id: "146", name: "Khiếu nại(Bộ Quốc phòng)" },
        { id: "7", name: "Khiếu nại, tố cáo(Bộ Công an)" },
        { id: "155", name: "Kho bạc(Bộ Tài chính)" },
        { id: "16502", name: "Kho bạc nhà nước(Bộ Tài chính)" },
        { id: "13714", name: "Khoa học, công nghệ(Bộ Công Thương)" },
        { id: "16183", name: "Khoa học công nghệ(Bộ Tài chính)" },
        { id: "235", name: "Khoa học công nghệ và môi trường(Bộ Xây dựng)" },
        { id: "14949", name: "Khoa học quân sự(Bộ Quốc phòng)" },
        { id: "118", name: "Khoa học và Công nghệ(Bộ Nông nghiệp và Môi trường)" },
        { id: "16282", name: "Khoáng sản(Bộ Công Thương)" },
        { id: "14955", name: "Kiểm định an toàn kỹ thuật và bảo vệ môi trường của xe cơ giới, xe chuyên dùng(Bộ Công an)" },
        { id: "137", name: "Kiểm định an toàn lao động(Bộ Quốc phòng)" },
        { id: "14322", name: "Kiểm định chất lượng giáo dục(Bộ Giáo dục và Đào tạo)" },
        { id: "14742", name: "Kiểm định kỹ thuật an toàn lao động(Bộ Xây dựng)" },
        { id: "14662", name: "Kiểm lâm(Bộ Nông nghiệp và Môi trường)" },
        { id: "14682", name: "Kiểm ngư(Bộ Nông nghiệp và Môi trường)" },
        { id: "14842", name: "Kiểm soát thủ tục hành chính(Văn phòng Chính phủ)" },
        { id: "15582", name: "Kiểm tra kiến thức pháp luật về trật tự, an toàn giao thông đường bộ(Bộ Công an)" },
        { id: "236", name: "Kinh doanh bất động sản(Bộ Xây dựng)" },
        { id: "22", name: "Kinh doanh khí(Bộ Công Thương)" },
        { id: "119", name: "Kinh tế hợp tác và Phát triển nông thôn(Bộ Nông nghiệp và Môi trường)" },
        { id: "237", name: "Kinh tế xây dựng(Bộ Xây dựng)" },
        { id: "14963", name: "Kết hợp quốc phòng với kinh tế - xã hội(Bộ Quốc phòng)" },
        { id: "14970", name: "Ký kết, gia nhập điều ước quốc tế, thoả thuận quốc tế(Bộ Quốc phòng)" },
        { id: "219", name: "Lữ hành(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "222", name: "Lễ hội(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "78", name: "Lao động(Bộ Nội vụ)" },
        { id: "15962", name: "Lao động, Thương binh và Xã hội(Bộ Công Thương)" },
        { id: "16482", name: "Lao động, tiền lương(Bộ Nội vụ)" },
        { id: "15702", name: "Lao động, tiền lương, quan hệ lao động(Bộ Nội vụ)" },
        { id: "16262", name: "Lao động, tiền lương và bảo hiểm xã hội(Bộ Nội vụ)" },
        { id: "120", name: "Lâm nghiệp(Bộ Nông nghiệp và Môi trường)" },
        { id: "16103", name: "LĨNH VỰC CÔNG TÁC QUỐC PHÒNG Ở BỘ, NGÀNH TRUNG ƯƠNG, ĐỊA PHƯƠNG(Bộ Quốc phòng)" },
        { id: "191", name: "Lĩnh vực khác(Bộ Khoa học và Công nghệ)" },
        { id: "16162", name: "LĨNH VỰC KẾT HỢP QUỐC PHÒNG VỚI KINH TẾ - XÃ HỘI(Bộ Quốc phòng)" },
        { id: "16142", name: "LĨNH VỰC QUẢN LÝ HOẠT ĐỘNG KHẮC PHỤC HẬU QUẢ BOM MÌN VẬT NỔ SAU CHIẾN TRANH(Bộ Quốc phòng)" },
        { id: "205", name: "Luật sư(Bộ Tư pháp)" },
        { id: "23", name: "Lưu thông hàng hóa trong nước(Bộ Công Thương)" },
        { id: "15622", name: "Lý lịch tư pháp(Bộ Công an)" },
        { id: "253", name: "Mỹ phẩm(Bộ Y tế)" },
        { id: "223", name: "Mỹ thuật, nhiếp ảnh, triển lãm(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "95", name: "Miễn thị thực(Bộ Ngoại giao)" },
        { id: "182", name: "Môi trường(Bộ Nông nghiệp và Môi trường)" },
        { id: "13852", name: "Mật mã dân sự(Bộ Quốc phòng)" },
        { id: "24", name: "Năng lượng(Bộ Công Thương)" },
        { id: "15442", name: "Ứng phó sự cố tràn dầu(Bộ Quốc phòng)" },
        { id: "156", name: "Ngân sách Nhà nước(Bộ Tài chính)" },
        { id: "15222", name: "Nghề thủ công mỹ nghệ(Bộ Công Thương)" },
        { id: "224", name: "Nghệ thuật biểu diễn(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "138", name: "Nghĩa vụ quân sự(Bộ Quốc phòng)" },
        { id: "15142", name: "Nghiên cứu khoa học(Bộ Tài chính)" },
        { id: "80", name: "Người có công(Bộ Nội vụ)" },
        { id: "83", name: "Người lao động Việt Nam đi làm việc ở nước ngoài theo hợp đồng(Bộ Nội vụ)" },
        { id: "238", name: "Nhà ở và công sở(Bộ Xây dựng)" },
        { id: "16023", name: "Nội vụ(Bộ Ngoại giao)" },
        { id: "13759", name: "Nông nghiệp(Bộ Nông nghiệp và Môi trường)" },
        { id: "15802", name: "Nông nghiệp và Môi trường(Bộ Nông nghiệp và Môi trường)" },
        { id: "14783", name: "Nông thôn mới(Bộ Nông nghiệp và Môi trường)" },
        { id: "207", name: "Nuôi con nuôi(Bộ Tư pháp)" },
        { id: "208", name: "Phổ biến giáo dục pháp luật(Bộ Tư pháp)" },
        { id: "14803", name: "Phổ biến, giáo dục pháp luật (nội bộ)(Bộ Tư pháp)" },
        { id: "15422", name: "Pháp chế(Bộ Xây dựng)" },
        { id: "172", name: "Pháp chế(Bộ Tài chính)" },
        { id: "111", name: "Pháp chế(Bộ Nội vụ)" },
        { id: "14822", name: "Pháp điển hệ thống quy phạm pháp luật(Bộ Tư pháp)" },
        { id: "190", name: "Phát thanh, truyền hình và thông tin điện tử(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "16422", name: "Phát triển doanh nghiệp nhà nước(Bộ Tài chính)" },
        { id: "239", name: "Phát triển đô thị(Bộ Xây dựng)" },
        { id: "257", name: "Phòng bệnh(Bộ Y tế)" },
        { id: "8", name: "Phòng cháy, chữa cháy(Bộ Công an)" },
        { id: "81", name: "Phòng, chống tệ nạn xã hội(Bộ Y tế)" },
        { id: "267", name: "Phòng, chống tham nhũng(Thanh tra Chính phủ)" },
        { id: "15944", name: "Phòng chống tham nhũng(Bộ Công Thương)" },
        { id: "25", name: "Phòng vệ thương mại(Bộ Công Thương)" },
        { id: "14002", name: "QUÂN SỰ, QUỐC PHÒNG(Bộ Quốc phòng)" },
        { id: "168", name: "Quốc phòng, an ninh(Bộ Tài chính)" },
        { id: "14805", name: "Quốc tịch(Bộ Tư pháp)" },
        { id: "94", name: "Quốc tịch(Bộ Ngoại giao)" },
        { id: "210", name: "Quốc tịch(Bộ Tư pháp)" },
        { id: "14582", name: "Quản lý bán hàng đa cấp(Bộ Công Thương)" },
        { id: "139", name: "Quản lý biên giới(Bộ Quốc phòng)" },
        { id: "14945", name: "Quản lý biên giới(Bộ Quốc phòng)" },
        { id: "13712", name: "Quản lý bảo lãnh tín dụng của Nhà nước(Ngân hàng phát triển)" },
        { id: "231", name: "Quản lý chất lượng công trình xây dựng(Bộ Xây dựng)" },
        { id: "122", name: "Quản lý chất lượng nông lâm sản và thủy sản(Bộ Nông nghiệp và Môi trường)" },
        { id: "16582", name: "Quản lý chất lượng sản phẩm, hàng hoá(Bộ Công an)" },
        { id: "26", name: "Quản lý Cạnh tranh(Bộ Công Thương)" },
        { id: "143", name: "Quản lý công nghệ thông tin(Bộ Quốc phòng)" },
        { id: "157", name: "Quản lý công sản(Bộ Tài chính)" },
        { id: "14000", name: "Quản lý công trình quốc phòng, khu quân sự(Bộ Quốc phòng)" },
        { id: "240", name: "Quản lý doanh nghiệp(Bộ Xây dựng)" },
        { id: "123", name: "Quản lý doanh nghiệp(Bộ Nông nghiệp và Môi trường)" },
        { id: "121", name: "Quản lý Đê điều và Phòng, chống thiên tai(Bộ Nông nghiệp và Môi trường)" },
        { id: "15122", name: "Quản lý, điều hành chính sách điện năng(Bộ Công Thương)" },
        { id: "14964", name: "Quản lý đất quốc phòng(Bộ Quốc phòng)" },
        { id: "15023", name: "Quản lý đầu tư công(Bộ Tài chính)" },
        { id: "15022", name: "Quản lý đầu tư công (Vụ Tài chính - Kinh tế ngành)(Bộ Tài chính)" },
        { id: "15042", name: "Quản lý đầu tư công (Vụ Tổng hợp KTQD)(Bộ Tài chính)" },
        { id: "159", name: "Quản lý giá(Bộ Tài chính)" },
        { id: "14943", name: "Quản lý hoạt động khắc phục hậu quả bom mìn vật nổ sau chiến tranh(Bộ Quốc phòng)" },
        { id: "14004", name: "Quản lý hoạt động vật liệu nổ công nghiệp, tiền chất thuốc nổ(Bộ Quốc phòng)" },
        { id: "14944", name: "Quản lý khu kinh tế - quốc phòng(Bộ Quốc phòng)" },
        { id: "13752", name: "Quản lý lao động ngoài nước(Bộ Nội vụ)" },
        { id: "160", name: "Quản lý nợ(Bộ Tài chính)" },
        { id: "9", name: "Quản lý ngành nghề đầu tư, kinh doanh có điều kiện về an ninh, trật tự(Bộ Công an)" },
        { id: "13713", name: "Quản lý ngân sách nhà nước(Bộ Tài chính)" },
        { id: "15902", name: "quản lý ngoại thương(Bộ Công Thương)" },
        { id: "15084", name: "Quản lý nhà nước về hỗ trợ doanh nghiệp nhỏ và vừa(Bộ Tài chính)" },
        { id: "106", name: "Quản lý nhà nước về hội, quỹ(Bộ Nội vụ)" },
        { id: "15025", name: "Quản lý nhà nước về khu công nghiệp, khu kinh tế(Bộ Tài chính)" },
        { id: "16003", name: "Quản lý nhà nước về ký kết và thực hiện thoả thuận quốc tế(Bộ Ngoại giao)" },
        { id: "15762", name: "Quản lý nhà nước về thi đua, khen thưởng(Bộ Tư pháp)" },
        { id: "242", name: "Quản lý nhà và thị trường bất động sản(Bộ Xây dựng)" },
        { id: "13802", name: "Quản lý quỹ ngân sách, quỹ dự trữ nhà nước và các quỹ tài chính khác của Nhà nước(Bộ Tài chính)" },
        { id: "16204", name: "Quản lý, sử dụng vốn hỗ trợ phát triển chính thức (ODA) và vốn vay ưu đãi của nhà tài trợ nước ngoài(Bộ Tài chính)" },
        { id: "14200", name: "Quản lý sử dụng vũ khí, súng săn, vật liệu nổ, công cụ hỗ trợ(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14946", name: "Quản lý sĩ quan dự bị(Bộ Quốc phòng)" },
        { id: "15682", name: "Quản lý tài sản công(Bộ Tài chính)" },
        { id: "15128", name: "Quản lý thị trường(Bộ Công Thương)" },
        { id: "13701", name: "Quản lý thuế, phí, lệ phí và thu khác của ngân sách nhà nước(Bộ Tài chính)" },
        { id: "13710", name: "Quản lý Tín dụng của Nhà nước(Ngân hàng phát triển)" },
        { id: "13709", name: "Quản lý vốn uỷ thác(Ngân hàng phát triển)" },
        { id: "10", name: "Quản lý vũ khí, vật liệu nổ, công cụ hỗ trợ và pháo(Bộ Công an)" },
        { id: "140", name: "Quản lý vùng trời(Bộ Quốc phòng)" },
        { id: "124", name: "Quản lý xây dựng công trình(Bộ Nông nghiệp và Môi trường)" },
        { id: "14969", name: "Quản lý xúc tiến đầu tư(Bộ Quốc phòng)" },
        { id: "11", name: "Quản lý xuất nhập cảnh(Bộ Công an)" },
        { id: "209", name: "Quản tài viên(Bộ Tư pháp)" },
        { id: "15822", name: "Quản trị - Văn phòng(Bộ Y tế)" },
        { id: "226", name: "Quảng cáo(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "243", name: "Quy  hoạch  đô thị  và  nông  thôn, kiến trúc(Bộ Xây dựng)" },
        { id: "15102", name: "Quy chế làm việc(Văn phòng Chính phủ)" },
        { id: "15302", name: "Quy hoạch(Bộ Tài chính)" },
        { id: "15024", name: "Quy hoạch (Quản lý quy hoạch)(Bộ Tài chính)" },
        { id: "27", name: "Sở giao dịch hàng hóa(Bộ Công Thương)" },
        { id: "69", name: "Sở hữu trí tuệ(Bộ Khoa học và Công nghệ)" },
        { id: "15623", name: "Sát hạch, cấp giấy phép lái xe(Bộ Công an)" },
        { id: "15782", name: "Sản xuất, lắp ráp ô tô(Bộ Công Thương)" },
        { id: "107", name: "Tổ chức - Biên chế(Bộ Nội vụ)" },
        { id: "15003", name: "Tổ chức bộ máy(Bộ Nội vụ)" },
        { id: "16022", name: "Tổ chức bộ máy(Bộ Ngoại giao)" },
        { id: "15763", name: "Tổ chức bộ máy(Bộ Tư pháp)" },
        { id: "15624", name: "Tổ chức cai nghiên ma túy và quản lý sau cai nghiện(Bộ Công an)" },
        { id: "12", name: "Tổ chức, cán bộ(Bộ Công an)" },
        { id: "13704", name: "Tổ chức cán bộ(Ngân hàng chính sách)" },
        { id: "15242", name: "Tổ chức cán bộ(Thanh tra Chính phủ)" },
        { id: "255", name: "Tổ chức cán bộ(Bộ Y tế)" },
        { id: "170", name: "Tổ chức cán bộ(Bộ Tài chính)" },
        { id: "13950", name: "Tổ chức cán bộ(Bộ Nội vụ)" },
        { id: "105", name: "Tổ chức cán bộ(Bộ Nội vụ)" },
        { id: "15043", name: "Tổ chức cán bộ/Đào tạo, bồi dưỡng/Thi đua khen thưởng/Sáng kiến(Bộ Tài chính)" },
        { id: "14922", name: "Tài chính - Kế toán(Bộ Nội vụ)" },
        { id: "16182", name: "Tài chính - Kinh tế ngành(Bộ Tài chính)" },
        { id: "163", name: "Tài chính doanh nghiệp(Bộ Tài chính)" },
        { id: "15522", name: "Tài chính đất đai(Bộ Tài chính)" },
        { id: "165", name: "Tài chính ngân hàng(Bộ Tài chính)" },
        { id: "254", name: "Tài chính y tế(Bộ Y tế)" },
        { id: "183", name: "Tài nguyên nước(Bộ Nông nghiệp và Môi trường)" },
        { id: "15322", name: "Tài sản kết cấu hạ tầng chợ do Nhà nước đầu tư, quản lý(Bộ Công Thương)" },
        { id: "15162", name: "Tài vụ - nội bộ(Bộ Tài chính)" },
        { id: "15402", name: "test3(Bảo hiểm xã hội)" },
        { id: "228", name: "Thể dục thể thao(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14222", name: "Thừa phát lại(Bộ Tư pháp)" },
        { id: "61", name: "Thành lập và hoạt động của doanh nghiệp(Bộ Tài chính)" },
        { id: "62", name: "Thành lập và hoạt động của hợp tác xã(Bộ Tài chính)" },
        { id: "66", name: "Thành lập và hoạt động của quỹ đầu tư khởi nghiệp sáng tạo(Bộ Tài chính)" },
        { id: "14150", name: "Thành lập và hoạt động của tổ hợp tác(Bộ Tài chính)" },
        { id: "63", name: "Thành lập và hoạt động của tổ hợp tác, hợp tác xã, liên hiệp hợp tác xã(Bộ Tài chính)" },
        { id: "64", name: "Thành lập và hoạt động doanh nghiệp (hộ kinh doanh)(Bộ Tài chính)" },
        { id: "65", name: "Thành lập và hoạt động doanh nghiệp xã hội(Bộ Tài chính)" },
        { id: "258", name: "Thành lập và hoạt động ngân hàng(Ngân hàng Nhà nước Việt Nam)" },
        { id: "14482", name: "Thành lập và sắp xếp lại doanh nghiệp do Nhà nước nắm giữ 100 phần trăm vốn điều lệ(Bộ Tài chính)" },
        { id: "16423", name: "Thanh toán chi phí tố tụng(Bộ Tài chính)" },
        { id: "15742", name: "Thanh tra(Bộ Y tế)" },
        { id: "171", name: "Thanh tra(Bộ Tài chính)" },
        { id: "15482", name: "Thanh tra(Thanh tra Chính phủ)" },
        { id: "102", name: "Thanh tra Bộ(Bộ Nội vụ)" },
        { id: "13761", name: "Thực hiện chính sách BHXH(Bộ Tài chính)" },
        { id: "13800", name: "Thực hiện chính sách BHYT(Bộ Tài chính)" },
        { id: "161", name: "Thi đua - khen thưởng(Bộ Tài chính)" },
        { id: "103", name: "Thi đua - khen thưởng(Bộ Nội vụ)" },
        { id: "229", name: "Thi đua – Khen thưởng(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14902", name: "Thi đua - Khen thưởng(Bộ Nội vụ)" },
        { id: "14303", name: "Thi đua, khen thưởng(Bộ Y tế)" },
        { id: "28", name: "Thi đua, khen thưởng(Bộ Công Thương)" },
        { id: "14903", name: "Thi đua khen thưởng(Bộ Nông nghiệp và Môi trường)" },
        { id: "211", name: "Thi hành án dân sự(Bộ Tư pháp)" },
        { id: "14804", name: "Thi hành án dân sự(Bộ Tư pháp)" },
        { id: "14966", name: "Thi hành án dân sự(Bộ Quốc phòng)" },
        { id: "245", name: "Thí nghiệm chuyên ngành xây dựng(Bộ Xây dựng)" },
        { id: "47", name: "Thi, tuyển sinh(Bộ Giáo dục và Đào tạo)" },
        { id: "256", name: "Thiết bị y tế(Bộ Y tế)" },
        { id: "14762", name: "Thông tin báo chí(Bộ Tư pháp)" },
        { id: "193", name: "Thông tin cơ sở(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "194", name: "Thông tin đối ngoại(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "15982", name: "Thông tin liên lạc quân sự(Bộ Quốc phòng)" },
        { id: "15943", name: "Thông tin và Truyền thông(Bộ Công Thương)" },
        { id: "16105", name: "Thông tin và Truyền thông(Bộ Y tế)" },
        { id: "166", name: "Thuế(Bộ Tài chính)" },
        { id: "13763", name: "Thu BHXH, BHYT, BHTN, BH tai nạn lao động, BNN(Bộ Tài chính)" },
        { id: "125", name: "Thú y(Bộ Nông nghiệp và Môi trường)" },
        { id: "225", name: "Thư viện(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "29", name: "Thương mại biên giới và miền núi(Bộ Công Thương)" },
        { id: "30", name: "Thương mại điện tử(Bộ Công Thương)" },
        { id: "31", name: "Thương mại quốc tế(Bộ Công Thương)" },
        { id: "126", name: "Thủy lợi(Bộ Nông nghiệp và Môi trường)" },
        { id: "127", name: "Thủy sản(Bộ Nông nghiệp và Môi trường)" },
        { id: "70", name: "Tiêu chuẩn đo lường chất lượng(Bộ Khoa học và Công nghệ)" },
        { id: "32", name: "Tiêu chuẩn đo lường chất lượng(Bộ Công Thương)" },
        { id: "48", name: "Tiêu chuẩn nhà giáo, cán bộ quản lý giáo dục(Bộ Giáo dục và Đào tạo)" },
        { id: "167", name: "Tin học - Thống kê(Bộ Tài chính)" },
        { id: "79", name: "Tiền lương(Bộ Nội vụ)" },
        { id: "104", name: "Tiền lương(Bộ Nội vụ)" },
        { id: "108", name: "Tín ngưỡng, tôn giáo(Dân tộc và Tôn giáo)" },
        { id: "270", name: "Tiếp công dân(Thanh tra Chính phủ)" },
        { id: "15125", name: "Tiết kiệm năng lượng(Bộ Công Thương)" },
        { id: "192", name: "Tần số vô tuyến điện(Bộ Khoa học và Công nghệ)" },
        { id: "109", name: "Tổng hợp(Bộ Nội vụ)" },
        { id: "184", name: "Tổng hợp(Bộ Nông nghiệp và Môi trường)" },
        { id: "14242", name: "Tòa án(Toàn án nhân dân tối cao)" },
        { id: "16223", name: "Trẻ em(Bộ Y tế)" },
        { id: "212", name: "Trợ giúp pháp lý(Bộ Tư pháp)" },
        { id: "213", name: "Trọng tài thương mại(Bộ Tư pháp)" },
        { id: "128", name: "Trồng trọt(Bộ Nông nghiệp và Môi trường)" },
        { id: "114", name: "Trồng trọt và Bảo vệ thực vật(Bộ Nông nghiệp và Môi trường)" },
        { id: "14722", name: "TTHCNOIBO-Chế độ chính sách cán bộ (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14727", name: "TTHCNOIBO-Chuyển đổi số quốc gia và Chính phủ số (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14712", name: "TTHCNOIBO-Đào tạo, bồi dưỡng (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14726", name: "TTHCNOIBO-Đoàn ra (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14705", name: "TTHCNOIBO-Hợp tác quốc tế (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14725", name: "TTHCNOIBO-Kế hoạch - Tài chính (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "13702", name: "TTHCNOIBO-Khoa học và Công nghệ (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14707", name: "TTHCNOIBO-Kiểm soát thủ tục hành chính (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14709", name: "TTHCNOIBO-Lưu trữ (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14703", name: "TTHCNOIBO-Nhân sự (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14724", name: "TTHCNOIBO-Pháp chế (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14711", name: "TTHCNOIBO-Quản lý tài sản (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14704", name: "TTHCNOIBO-Tổ chức (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14723", name: "TTHCNOIBO-Thi đua - Khen thưởng (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14702", name: "TTHCNOIBO-Thông tin, tuyên truyền (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14710", name: "TTHCNOIBO-Tổng hợp (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "14708", name: "TTHCNOIBO-Văn thư (Lĩnh vực TTHC nội bộ)(Bộ Khoa học và Công nghệ)" },
        { id: "141", name: "Tuyển sinh quân sự(Bộ Quốc phòng)" },
        { id: "14782", name: "Tư pháp(Bộ Tư pháp)" },
        { id: "214", name: "Tư vấn pháp luật(Bộ Tư pháp)" },
        { id: "14642", name: "Ưu đãi, miễn trừ(Bộ Ngoại giao)" },
        { id: "15083", name: "v(Bộ Kế hoạch và Đầu tư)" },
        { id: "13758", name: "Văn bằng, chứng chỉ(Bộ Giáo dục và Đào tạo)" },
        { id: "227", name: "Văn hóa(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "16122", name: "Văn phòng(Bộ Y tế)" },
        { id: "173", name: "Văn phòng(Bộ Tài chính)" },
        { id: "113", name: "Văn phòng(Bộ Nội vụ)" },
        { id: "110", name: "Văn thư và Lưu trữ nhà nước(Bộ Nội vụ)" },
        { id: "82", name: "Việc làm(Bộ Nội vụ)" },
        { id: "15304", name: "Viện Nghiên cứu Quản lý kinh tế Trung ương(Bộ Kế hoạch và Đầu tư)" },
        { id: "185", name: "Viễn thám(Bộ Nông nghiệp và Môi trường)" },
        { id: "195", name: "Viễn thông và Internet(Bộ Khoa học và Công nghệ)" },
        { id: "15062", name: "Viện trợ không hoàn lại không thuộc hỗ trợ phát triển chính thức của các cơ quan, tổ chức, cá nhân nước ngoài dành cho Việt Nam(Bộ Tài chính)" },
        { id: "16342", name: "Vận chuyển hàng hóa nguy hiểm(Bộ Công Thương)" },
        { id: "33", name: "Vật liệu nổ công nghiệp, tiền chất thuốc nổ(Bộ Công Thương)" },
        { id: "244", name: "Vật liệu xây dựng(Bộ Xây dựng)" },
        { id: "271", name: "Xử lý đơn thư(Thanh tra Chính phủ)" },
        { id: "15942", name: "Xử lý vi phạm hành chính(Bộ Công Thương)" },
        { id: "15922", name: "Xây dựng, ban hành văn bản QPPL(Bộ Công Thương)" },
        { id: "16024", name: "Xây dựng ngành(Bộ Ngoại giao)" },
        { id: "15743", name: "Xây dựng pháp luật(Bộ Y tế)" },
        { id: "14802", name: "Xây dựng pháp luật(Bộ Tư pháp)" },
        { id: "15002", name: "Xây dựng văn bản quy phạm pháp luật(Bộ Tư pháp)" },
        { id: "142", name: "Xe - máy quân sự(Bộ Quốc phòng)" },
        { id: "16082", name: "Xe - máy quân sự(Bộ Quốc phòng)" },
        { id: "35", name: "Xúc tiến thương mại(Bộ Công Thương)" },
        { id: "196", name: "Xuất Bản, In và Phát hành(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "34", name: "Xuất nhập khẩu(Bộ Công Thương)" },
        { id: "13803", name: "Xuất nhập khẩu văn hóa phẩm không nhằm mục đích kinh doanh(Bộ Văn hóa, Thể thao và Du lịch)" },
        { id: "14302", name: "Y Dược cổ truyền(Bộ Y tế)" },
    ],
    implementationLevels: [
        { id: "1", name: "Cấp Tỉnh" },
        { id: "2", name: "Cấp Xã" },
    ],
    targetAudiences: [
        { id: "4", name: "Cán bộ, công chức, viên chức" },
        { id: "1", name: "Công dân Việt Nam" },
        { id: "5", name: "Doanh nghiệp" },
        { id: "6", name: "Doanh nghiệp có vốn đầu tư nước ngoài" },
        { id: "9", name: "Hợp tác xã" },
        { id: "3", name: "Người nước ngoài" },
        { id: "2", name: "Người Việt Nam định cư ở nước ngoài" },
        { id: "7", name: "Tổ chức (không bao gồm doanh nghiệp, HTX)" },
        { id: "8", name: "Tổ chức nước ngoài" },
    ],
};

