[install]
# Tối ưu hóa cache và performance
cache = true
# Sử dụng lockfile để đảm bảo consistency
lockfile = true
# Tự động install peer dependencies
auto = true
# Sử dụng exact versions để tránh conflicts
exact = false

[install.scopes]
# Cấu hình scopes nếu cần

[run]
# Tối ưu hóa runtime performance - sử dụng Bun runtime
bun = true

[test]
# Cấu hình test runner
preload = ["./src/test/setup.ts"]

[build]
# Tối ưu hóa build performance
target = "browser"
minify = true
splitting = true
# Sử dụng Bun's native bundler
bundler = "bun"
